### ISSUE TITLE
revise keywords

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#138]
![image](https://user-images.githubusercontent.com/8794646/35921445-95d9ace2-0be8-11e8-8a98-cc533e7628de.png)

remove path, 1_010, etc.

**Comment by shuiblue** [comment]
![image](https://user-images.githubusercontent.com/8794646/35921787-aa5972a0-0be9-11e8-9ffb-317e090e25fa.png)
 stop word, and , the

**Comment by FancyCoder0** [comment]
https://github.com/FancyCoder0/INFOX/commit/d9b6799e9589bf0cb07e93131921ce1513681c70

fixed. need to test for verification.
