### ISSUE TITLE
Exporting infox data

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#141]
1. Is that possible to include the ' list of changed files' in the export table? it would be better to add the diff information for each changed file (e,g., file 1- add 3 LOC, delete 2 LOC) as well.

2. this might not be important or useful, but the pdf version is buggy:
![image](https://user-images.githubusercontent.com/8794646/36645683-93d3109a-1a3a-11e8-93a5-4db89babae39.png)
maybe remove the pdf version.

**Comment by FancyCoder0** [comment]
for 1, do you mean that I should also count the deleted line for fork ?
for 2, ok. Let me remove pdf.
