### ISSUE TITLE
Search followed repo

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#144]
Is there a way to search for the repo that I am following?
When the number of followed repos increased, it is hard for user to find certain repo.

**Comment by FancyCoder0** [comment]
Good idea. I will try use something like "smart search" to solve that.

**Comment by FancyCoder0** [comment]
done. https://github.com/FancyCoder0/INFOX/commit/fcee04f1f60407258c101bb4268d045738903e8a
