### ISSUE TITLE
highlight keyword for searching result

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#149]
![image](https://user-images.githubusercontent.com/8794646/39391191-b20407f0-4a6d-11e8-9b37-83f3233667fb.png)

After searching keyword 'filament', it would be better to high light the 'filament' word in earch fork

**Comment by FancyCoder0** [comment]
Good idea.
Here is a possible solution I found: https://datatables.net/blog/2014-10-22

**Comment by FancyCoder0** [comment]
done. https://github.com/FancyCoder0/INFOX/commit/313eede8ee730b72cb10c8a6443a48ae8638f3c5

![image](https://user-images.githubusercontent.com/7541296/39391774-73930b06-4adb-11e8-93f7-d59c445566e8.png)

**Comment by shuiblue** [comment]
good job!

**Comment by shuiblue** [comment]
light green/Yellow would be better I think.

**Comment by FancyCoder0** [comment]
done.
