### ISSUE TITLE
Table font size

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#20]
![image](https://user-images.githubusercontent.com/8794646/33862813-990305f2-deb2-11e7-829d-904d942b9d3e.png)

- font size is too big
- table is bigger than browser

**Comment by shuiblue** [comment]
![image](https://user-images.githubusercontent.com/8794646/33862865-ed0650dc-deb2-11e7-940e-9af3564b04f0.png)
remove this title

**Comment by FancyCoder0** [comment]
tried but failed. Now I only can implement a scroll

**Comment by FancyCoder0** [comment]
laborious bug. Long time to fix.
finally, I find out that it because of the table need to fit the size of bottom " input type="text" ".
