### ISSUE TITLE
navigation bar

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#22]
![image](https://user-images.githubusercontent.com/8794646/33862954-6785009c-deb3-11e7-8f70-01f374e04487.png)
change 'add manually'  --> 'Find repos'
remove 'discover'

**Comment by shuiblue** [comment]
![image](https://user-images.githubusercontent.com/8794646/33863038-e26f77f6-deb3-11e7-83e7-7a886d3d55ac.png)
'Dashboard' is not intuitive. I would recommend change it as 'Followed Repos'


refer to coveralls.io:
![image](https://user-images.githubusercontent.com/8794646/33863034-dacc925e-deb3-11e7-9d85-b04814d7dc33.png)

**Comment by FancyCoder0** [comment]
fixed.
