### ISSUE TITLE
move tag column to the end

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#30]
![image](https://user-images.githubusercontent.com/8794646/34015230-d330370a-e0eb-11e7-8a9e-e6d979e51723.png)

- move tag column to the end
- rename 'tag' as ' Your Tag '

**Comment by FancyCoder0** [comment]
I think Tag is okay. The tag info is now public.

**Comment by FancyCoder0** [comment]
fixed.
