### ISSUE TITLE
Layout and text changes

### ISSUE THREAD

**Issue by ckaestne** [FancyCoder0/INFOX#37]
see https://docs.google.com/document/d/1A_IUSRkescj3zV3VGVJWepE59tXCl5bC68sSLe_PRzA/edit?usp=sharing for a list of changes to text and layout please

**Comment by FancyCoder0** [comment]
I checked the docs again.
Seems like anything is done except issues already on github.
For "show all matching repositories"(eg. smart search), it could be done by using github API, already added into issues.
As for "Add repository", you can see now I use two page: "Import your Repository" and "Search on GitHub" which seems like clearly enough. I agree we could merge this two pages together, let me try when finish "smart search".


Thanks for all this meticulous issues.
