### ISSUE TITLE
datebase not support key contain '.'

### ISSUE THREAD

**Issue by FancyCoder0** [FancyCoder0/INFOX#43]
Because mongoDB don't support key value contains '.' .
It's really troublesome....

**Comment by shuiblue** [comment]
possible solution:

1. https://github.com/mongodb-js/extended-json/issues/14
2. https://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name
![image](https://user-images.githubusercontent.com/8794646/36645365-8c116708-1a35-11e8-806d-b99d93ddd092.png)

**Comment by FancyCoder0** [comment]
Since like it can be added & followed, but the database will throw error. Don't know why.
