### ISSUE TITLE
sleep 2 sec

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#48]
sleep 2 seconds when querying github api. (for current version)

**Comment by FancyCoder0** [comment]
![7myeg_f-thumbnail-100-0_s-600x0](https://user-images.githubusercontent.com/7541296/34077925-9620bca2-e34a-11e7-8d30-1fc55bee080a.jpg)

**Comment by FancyCoder0** [comment]
![screen shot 2017-12-17 at 16 51 12](https://user-images.githubusercontent.com/7541296/34077927-a5427ee6-e34a-11e7-80fc-943a6311fc4f.png)

**Comment by FancyCoder0** [comment]
Let's open another issues.
