### ISSUE TITLE
setup email

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#49]
refer: https://kinsta.com/knowledgebase/free-smtp-server/

**Comment by FancyCoder0** [comment]
Could you help me write the email template : https://github.com/FancyCoder0/INFOX/blob/master/app/templates/email.html ?

**Comment by shuiblue** [comment]
SURE. I am signing up a gmail account now. I will write the email template and submit PR

**Comment by FancyCoder0** [comment]
I use jinja2 to render the template. You may need to add like {{ username }} in html. See an example:  https://github.com/FancyCoder0/INFOX/blob/master/app/templates/_projects.html#L35

**Comment by FancyCoder0** [comment]
done.
