### ISSUE TITLE
load repo button

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#53]
![image](https://user-images.githubusercontent.com/8794646/34076690-a834d330-e2bc-11e7-8881-29dcb56bfa6b.png)
![image](https://user-images.githubusercontent.com/8794646/34076693-ae53b3a8-e2bc-11e7-8457-ccb0e539cb83.png)

put these two button together..,

**Comment by shuiblue** [comment]
wait,,, 'sync with github ' is about sync followed forks, I think it should be in the 'repositories page' ?

**Comment by FancyCoder0** [comment]
no，sync with github is updating your owned/forked repos on Github，not the data in INFOX.

**Comment by shuiblue** [comment]
I see. Then put them together would be find

**Comment by FancyCoder0** [comment]
I don't think so. Now the layout is fine.
