### ISSUE TITLE
Repeated Changed Files

### ISSUE THREAD

**Issue by FancyCoder0** [FancyCoder0/INFOX#54]
![screen shot 2017-12-17 at 17 07 18](https://user-images.githubusercontent.com/7541296/34078025-ef6f6c3e-e34c-11e7-82cd-10a793076819.png)

Now, there are three ways to get diff code.

1. Crawler online: like https://github.com/cenkalti/github-flask/compare/master...tylertreat:master
My code: https://github.com/FancyCoder0/INFOX/blob/f9f0ab2e144c4eb1c1c13feff7d7255b34018f23/app/analyse/compare_changes_crawler.py

2. add '.patch' suffix But here is the problem that the file will be repeated(all changed history). See here: https://github.com/cenkalti/github-flask/compare/master...tylertreat:master.patch
Now it's the current version.

3. Use diff on local machine , not implement yet

Another problem is that to show user the location of the changed code, now only way 1 can support(link to github diff page).

**Comment by FancyCoder0** [comment]
Now, I output distinct elements in list.

**Comment by shuiblue** [comment]
what is the current status?

**Comment by FancyCoder0** [comment]
use compare_url + ".diff" , no repeat files.
