### ISSUE TITLE
"Activate fork" -> "Active forks"

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#61]
![image](https://user-images.githubusercontent.com/8794646/34081659-7d32516e-e31e-11e7-9e72-5a961794140f.png)
![image](https://user-images.githubusercontent.com/8794646/34081665-8f0699c2-e31e-11e7-9e87-5d5e832b63c6.png)

**Comment by shuiblue** [comment]
#62

**Comment by FancyCoder0** [comment]
done.
