### ISSUE TITLE
corner cases (need discussion)

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#70]
![image](https://user-images.githubusercontent.com/8794646/34089104-d89fff08-e37b-11e7-8934-7b69077a3eac.png)

https://github.com/google/protobuf/compare/master...farazfazli:master
![image](https://user-images.githubusercontent.com/8794646/34089119-fd0d0214-e37b-11e7-8fda-8c29a7879347.png)

**Comment by FancyCoder0** [comment]
word-break is also unbeautiful. My idea is that only keep length(key_word) < constant.
