### ISSUE TITLE
find repo page

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#89]
![image](https://user-images.githubusercontent.com/8794646/34234808-7bd46b0a-e5bb-11e7-8d19-80b03721a32f.png)

the space in the left side is wasted.
I think we could list the search component and the 'hot repo' vertically.

**Comment by FancyCoder0** [comment]
I have tried vertically, it's not beautiful I think. :)

**Comment by shuiblue** [comment]
![image](https://user-images.githubusercontent.com/8794646/34237623-b4bc4540-e5cb-11e7-88f5-99edec1ff482.png)
I think we could make it similar to the layout of 'followed repos' page

**Comment by FancyCoder0** [comment]
And the search engine is above the content?

**Comment by shuiblue** [comment]
put the search engine under 'find repos on GitHub'
or above the content.

whichever is easier to you.
