### ISSUE TITLE
Update repo list

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#90]
make repo cannot be selected again after it has been followed in INFOX

![image](https://user-images.githubusercontent.com/8794646/34237447-be6f4444-e5ca-11e7-9b88-be29a25b73f9.png)
![image](https://user-images.githubusercontent.com/8794646/34237455-c625ded2-e5ca-11e7-9d8e-954e8f279486.png)

**Comment by FancyCoder0** [comment]
done.
