### ISSUE TITLE
keywords - treat repo name as stopword

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#91]
- treat repo name as a stop word
![image](https://user-images.githubusercontent.com/8794646/34237798-9fdd562c-e5cc-11e7-8a48-fd6ec07cbf65.png)

**Comment by FancyCoder0** [comment]
'has' in 'has_key', and 'has' -> 'ha' :)

**Comment by shuiblue** [comment]
I think we have discussed to keep the original version of the word?

**Comment by shuiblue** [comment]
![image](https://user-images.githubusercontent.com/8794646/34237927-31269e40-e5cd-11e7-86f2-7b51cbc36051.png)
'this' should not be in the keyword list, and 'this' is in the cplusplus_stopwords.txt

**Comment by shuiblue** [comment]
![image](https://user-images.githubusercontent.com/8794646/34237975-63ce7ce6-e5cd-11e7-8504-fcd49a80f902.png)
by merging 1-gram and 2-gram, the 2nd 'key' would be removed

**Comment by FancyCoder0** [comment]
for 'this' case, you can see it changes PHP files which I don't add stopwords yet.

**Comment by shuiblue** [comment]
can we add a general_stopword.txt?

**Comment by FancyCoder0** [comment]
yes, now I don't use 2-gram yet.

**Comment by FancyCoder0** [comment]
I think you can create another issue which makes discussion clearly.

**Comment by shuiblue** [comment]
ok I will add"'calculating ifdef for 2_grams" in todo then

**Comment by FancyCoder0** [comment]
I think "treat repo name as stopword" is okay.
Anyway, it's a small problem.

**Comment by shuiblue** [comment]
We are identifying representative words for each fork, I think the repo's name is not representative.
If it is a small problem. pls fix it before our first release.

**Comment by FancyCoder0** [comment]
fixed
