### ISSUE TITLE
keywords - method ( need discussion)

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#95]
![image](https://user-images.githubusercontent.com/8794646/34240053-84ac0d0a-e5d9-11e7-8de5-75e757a7ca56.png)
https://github.com/MarlinFirmware/Marlin/compare/1.1.x...atom-bomb:Marlin_v1#diff-1cb08de130a6ece2d1b5b9c37bcfef48

**Comment by FancyCoder0** [comment]
this fork has been updated since crawlered.
