### ISSUE TITLE
stop file suffix txt ?

### ISSUE THREAD

**Issue by shuiblue** [FancyCoder0/INFOX#96]
![image](https://user-images.githubusercontent.com/8794646/34240348-49e1b448-e5db-11e7-8abd-84cc9e17b0f6.png)

files end with .proto are automatically generated files.
Do we need to add an stopfile.txt?

**Comment by FancyCoder0** [comment]
.proto is something like .xml, .ini. It may not be automatically generated, could be manually written.

**Comment by wasowski** [comment]
Yeah. @FancyCoder0 is right - proto is the model in the Google protocol buffers language. It is a simple data model.  I actually use this language as an example of a textual DSL in my course, so I accidentally know it :)
